### PR TITLE
Update to opentelemetry 0.14.0 

### PR DESCRIPTION
**Pull request by dobesv**

### CODE REVIEW

**Comment by mwear** [comment]
Hi @dobesv. Thanks for the contribution, however, this work is simultaneously being handled in this as part of #25, which will also include support for host metrics. I just wanted to check to see if this update is a major blocker for you or if you have a timeline for when we need these changes. #25 is very close to being ready, and we can shepherd that through. The holidays add some complications, but we can make something happen if you need it.

**Comment by dobesv** [comment]
We've worked around the issue for now so we're not waiting on this.

**Comment by mwear** [comment]
I appreciate your understanding and patience. We'll get #25 prepared and released in the near future.

**Comment by mwear** [comment]
@dobesv I just wanted to followup and let you know that the changes in #25 have been released in v0.13.0 of launcher: https://www.npmjs.com/package/lightstep-opentelemetry-launcher-node/v/0.13.0. Thanks for your patience!

**Pull request closed without merging**
